### ISSUE TITLE
为啥显示是高德地图而不是百度地图,如何让地图显示是百度地图

### ISSUE THREAD

**Issue by log-dragon** [xiaoguxg/android-cluster-marker-master#2]

**Comment by ChenZeFengHi** [comment]
同问为什么啊，百度地图的聚合太卡了！所以前来找解决方案！

**Comment by xiaogu-space** [comment]
![image](https://user-images.githubusercontent.com/8435230/29559980-2cf93e22-8763-11e7-8ef9-2a4ff7f93a0e.png)
切换到百度的分支
